language: python
python:
  - "3.6"
branches:
    only:
        - master
services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

before_script:
  - psql -c 'create database ApiTests;' -U postgres
  - python manage.py db upgrade

# command to run tests
script:
    - nosetests --with-coverage --cover-package=recipes
    - pylint app.py || exit 0
after_success:
  - coveralls
env:
  - TEST_DB = 'postgresql://localhost/ApiTests'