language: python
python:
  - "3.6"
branches:
    only:
        - develop
services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

env:
  global:
    - export SECRET_KEY='\xfd{H\xe5<\x95\xf9\xe3\x96.5\xd1\x01O<!\xd5\xa2\xa0\x9fR"\xa1\xa8'
    - export DATABASE_URL='postgresql://localhost/ApiTests'
    - export TEST_DB='postgresql://localhost/rest_api'


before_script:
  - sudo -u postgres createdb ApiTests
  - sudo -u postgres createdb rest_api
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

# command to run tests
script:
    - nosetests --with-coverage --cover-package=app
after_success:
  coveralls