language: python
python:
  - "3.6"
branches:
    only:
        - master
services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

before_script:
  - echo "DEBUG=True" >> .env
  - echo "DATABASE_URL=postgresql://localhost/rest_api" >> .env
  - echo "TEST_DB=postgresql://localhost/ApiTests" >> .env
  - sudo -u postgres createdb ApiTests
  - sudo -u postgres createdb rest_api
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

# command to run tests
script:
    - nosetests --with-coverage --cover-package=recipes
after_success:
  coveralls